# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.TimeField(blank=True),
        ),
    ]
