# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_alert', '0002_auto_20180323_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.TimeField(blank=True, default=models.TimeField()),
        ),
    ]
