# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-24 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_alert', '0003_auto_20180323_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intervals',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 3, 24, 15, 55, 21, 800188)),
        ),
    ]
