# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sms_alert', '0005_auto_20180325_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sleeping_hours',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='US/Pacific'),
        ),
        migrations.AddField(
            model_name='user',
            name='wake_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 27, 21, 20, 26, 993741)),
        ),
        migrations.AlterField(
            model_name='user',
            name='sleep_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 27, 21, 20, 26, 993741)),
        ),
    ]
