# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_alert', '0006_auto_20180327_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='intervals',
        ),
        migrations.AlterField(
            model_name='user',
            name='sleep_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 28, 0, 13, 10, 49700)),
        ),
        migrations.AlterField(
            model_name='user',
            name='wake_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 28, 0, 13, 10, 49700)),
        ),
    ]
